version: '3'
services:
  rock:
    #image: obiba/rock:snapshot
    build: .
    ports:
      - ${PORT}:8085
    environment:
      - ROCK_CLUSTER=${ROCK_CLUSTER}
      - ROCK_TAGS=${ROCK_TAGS}
      # for self-registration
      #- ROCK_SERVER=${ROCK_SERVER}
      #- ROCK_OPAL_SERVER=${ROCK_OPAL_SERVER}
      #- ROCK_OPAL_TOKEN=${ROCK_OPAL_TOKEN}
    volumes:
      - ${PROJECT_HOME}/rock_home:/srv
