version: '3'
services:
        rock:
                #image: obiba/rock:snapshot
                build: .
                environment:
                        - ROCK_ADMINISTRATOR_NAME=administrator
                        - ROCK_ADMINISTRATOR_PASSWORD=password
                        - ROCK_MANAGER_NAME=manager
                        - ROCK_MANAGER_PASSWORD=password
                        - ROCK_USER_NAME=user
                        - ROCK_USER_PASSWORD=password
                        - ROCK_ID=rock-demo
                        - ROCK_TAGS=default
                        - ROCK_ADDRESS=https://rock-demo.obiba.org
                volumes:
                        - /tmp/rock:/srv
