services:
  rock:
    image: obiba/rock:latest
    #image: obiba/rock:test
    ports:
      - 8885:8085
    #environment:
      #- ROCK_ADMINISTRATOR_NAME=${ROCK_ADMINISTRATOR_NAME}
      #- ROCK_ADMINISTRATOR_PASSWORD=${ROCK_ADMINISTRATOR_PASSWORD}
      #- ROCK_MANAGER_NAME=${ROCK_MANAGER_NAME}
      #- ROCK_MANAGER_PASSWORD=${ROCK_MANAGER_PASSWORD}
      #- ROCK_USER_NAME=${ROCK_USER_NAME}
      #- ROCK_USER_PASSWORD=${ROCK_USER_PASSWORD}
      #- ROCK_ID=${ROCK_ID}
      #- ROCK_CLUSTER=${ROCK_CLUSTER}
      #- ROCK_TAGS=${ROCK_TAGS}
      # for self-registration
      #- ROCK_SERVER=${ROCK_SERVER}
      #- ROCK_OPAL_SERVER=${ROCK_OPAL_SERVER}
      #- ROCK_OPAL_TOKEN=${ROCK_OPAL_TOKEN}
    volumes:
      - /tmp/test-rock:/srv
