# Rserver controller port
server:
  port: 8085

# Cluster node
node:
  # server id
  id: @rock_id@
  # cluster name
  cluster: @rock_cluster@
  # informative tags
  tags: @rock_tags@
  # optional public address, required only for self-registration
  server: @rock_server@

# Consul service registry
consul:
  server: @rock_consul_server@
  token: @rock_consul_token@
  # health check interval
  interval: 10

# Opal app registry
opal:
  server: @rock_opal_server@
  token: @rock_opal_token@

# R executable path, required to launch Rserver
r:
  exec: /usr/bin/R
  repos: @rock_repos@

# Security
security:
  users:
    # administrator, can do all
    - id: @rock_administrator_name@
      secret: @rock_administrator_password@
      roles: administrator
    # manager of the R server and sessions, can manage the server but cannot use R
    - id: @rock_manager_name@
      secret: @rock_manager_password@
      roles: manager
    # R sessions user, can use R
    - id: @rock_user_name@
      secret: @rock_user_password@
      roles: user
